
     defTextBoxFocus=CopyForm1_TextFieldCstFullName,CopyForm1_TextFieldCstHouse,CopyForm1_TextFieldCstCity,CopyForm1_TextFieldPincode,CopyForm1_TextFieldCstEmail,CopyForm1_CstEmail,CopyForm1_TextFieldCstContactNumber,CopyForm1_TextFieldCstAppartment

     defTextAreaFocus=CopyForm1_TextAreaDes

     defListBoxFocus=CopyForm1_ListBoxServiceType,CopyForm1_ListBoxState,CopyForm1_ListBoxCountry
