
     defTextBoxFocus=Form1_TextFieldCstFullName,Form1_TextFieldCstHouse,Form1_TextFieldCstCity,Form1_TextFieldPincode,Form1_TextFieldCstEmail,Form1_TextFieldCstContactNumber,Form1_TextFieldCstAppartment

     defTextAreaFocus=Form1_TextAreaDes

     defListBoxFocus=Form1_ListBoxServiceType,Form1_ListBoxState,Form1_ListBoxCountry
