
     defTextBoxFocus=serviceBooking_TextFieldCstFullName,serviceBooking_TextFieldCstHouse,serviceBooking_TextFieldCstCity,serviceBooking_TextFieldPincode,serviceBooking_TextFieldCstEmail,serviceBooking_TextFieldCstContactNumber,serviceBooking_TextFieldCstAppartment

     defTextAreaFocus=serviceBooking_TextAreaDes

     defListBoxFocus=serviceBooking_ListBoxServiceType,serviceBooking_ListBoxState,serviceBooking_ListBoxCountry
